# Generated by Django 2.1.5 on 2019-02-06 20:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_discipline_focus_keyword_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherThemeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('researcher', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_theme_relationship', to='core.ResearcherPage')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_researcher_relationship', to='core.ThemePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
    ]
