# Generated by Django 2.1.5 on 2019-02-07 10:20

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_researcherthemerelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherpage',
            name='disciplines',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Discipline'),
        ),
    ]
