# Generated by Django 2.1.5 on 2019-02-07 11:53

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_researcherpage_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherpage',
            name='focus',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Focus'),
        ),
        migrations.AddField(
            model_name='researcherpage',
            name='keywords',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Keyword'),
        ),
        migrations.AddField(
            model_name='researcherpage',
            name='methods',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Method'),
        ),
    ]
