# Generated by Django 2.1.5 on 2019-02-07 15:30

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_facets_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='themepage',
            name='disciplines',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Discipline'),
        ),
        migrations.AddField(
            model_name='themepage',
            name='focus',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Focus'),
        ),
        migrations.AddField(
            model_name='themepage',
            name='keywords',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Keyword'),
        ),
        migrations.AddField(
            model_name='themepage',
            name='methods',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Method'),
        ),
    ]
