# Generated by Django 2.1.5 on 2019-02-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_projectpage_facets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherthemerelationship',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='researcherthemerelationship',
            name='theme',
        ),
        migrations.DeleteModel(
            name='ResearcherThemeRelationship',
        ),
    ]
