# Generated by Django 2.2.1 on 2019-05-16 13:12

from django.db import migrations
import kdl_wagtail.zotero.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_show_in_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='endnotes',
            field=wagtail.core.fields.StreamField([('note_block', wagtail.core.blocks.StreamBlock([('richtext_block', wagtail.core.blocks.RichTextBlock(icon='pilcrow', required=False, template='kdl_wagtail_core/blocks/richtext_block.html')), ('bibliography_block', wagtail.core.blocks.StructBlock([('entry', wagtail.snippets.blocks.SnippetChooserBlock(kdl_wagtail.zotero.models.Bibliography, required=True)), ('pages', wagtail.core.blocks.CharBlock(required=False)), ('shortnote', wagtail.core.blocks.BooleanBlock(required=False))], icon='form', required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='themepage',
            name='endnotes',
            field=wagtail.core.fields.StreamField([('note_block', wagtail.core.blocks.StreamBlock([('richtext_block', wagtail.core.blocks.RichTextBlock(icon='pilcrow', required=False, template='kdl_wagtail_core/blocks/richtext_block.html')), ('bibliography_block', wagtail.core.blocks.StructBlock([('entry', wagtail.snippets.blocks.SnippetChooserBlock(kdl_wagtail.zotero.models.Bibliography, required=True)), ('pages', wagtail.core.blocks.CharBlock(required=False)), ('shortnote', wagtail.core.blocks.BooleanBlock(required=False))], icon='form', required=False))]))], blank=True),
        ),
    ]
