# Generated by Django 2.2.1 on 2019-05-21 13:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kdl_wagtail_zotero', '0008_add_verbose_name_to_bibliography_fields'),
        ('core', '0030_projectendnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeEndnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('pre_text', wagtail.core.fields.RichTextField(null=True)),
                ('bibliography_pages', models.CharField(max_length=256, null=True)),
                ('bibliography_shortnote', models.BooleanField()),
                ('post_text', wagtail.core.fields.RichTextField(null=True)),
                ('bibliography_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kdl_wagtail_zotero.Bibliography')),
                ('theme', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='endnotes', to='core.ThemePage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
