# Generated by Django 2.2.1 on 2019-05-21 13:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_themeendnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectendnote',
            name='bibliography_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kdl_wagtail_zotero.Bibliography'),
        ),
        migrations.AlterField(
            model_name='projectendnote',
            name='bibliography_pages',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='projectendnote',
            name='post_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectendnote',
            name='pre_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themeendnote',
            name='bibliography_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kdl_wagtail_zotero.Bibliography'),
        ),
        migrations.AlterField(
            model_name='themeendnote',
            name='bibliography_pages',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='themeendnote',
            name='post_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themeendnote',
            name='pre_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
