# Generated by Django 2.2.1 on 2019-05-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_endnotemixin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectendnote',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='themeendnote',
            options={'ordering': ['sort_order']},
        ),
    ]
