# Generated by Django 2.2.2 on 2019-07-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_change_meta_on_endnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='full_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
