# Generated by Django 2.2.2 on 2019-08-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_projectpage_full_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
