# Generated by Django 2.2.2 on 2019-08-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_facettype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['facet_type', 'title']},
        ),
        migrations.AlterModelOptions(
            name='focus',
            options={'ordering': ['facet_type', 'title'], 'verbose_name_plural': 'Focus'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['facet_type', 'title']},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['facet_type', 'title']},
        ),
        migrations.AddField(
            model_name='discipline',
            name='facet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FacetType'),
        ),
        migrations.AddField(
            model_name='focus',
            name='facet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FacetType'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='facet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FacetType'),
        ),
        migrations.AddField(
            model_name='method',
            name='facet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FacetType'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='focus',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='method',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together={('facet_type', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='focus',
            unique_together={('facet_type', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('facet_type', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='method',
            unique_together={('facet_type', 'title')},
        ),
    ]
