# Generated by Django 2.2.2 on 2019-08-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_facettype_to_basefacet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='focus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='focus',
            name='facet_type',
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='facet_type',
        ),
        migrations.AlterUniqueTogether(
            name='method',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='method',
            name='facet_type',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='methods',
        ),
        migrations.RemoveField(
            model_name='researcherpage',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='researcherpage',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='researcherpage',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='researcherpage',
            name='methods',
        ),
        migrations.RemoveField(
            model_name='themepage',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='themepage',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='themepage',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='themepage',
            name='methods',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Focus',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
    ]
