# Generated by Django 2.2.2 on 2019-08-07 10:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_facet_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('facet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FacetType')),
            ],
            options={
                'unique_together': {('facet_type', 'title')},
                'ordering': ['facet_type', 'title'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
