# Generated by Django 2.2.2 on 2019-08-07 11:08

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_facet'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='facets',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Facet'),
        ),
        migrations.AddField(
            model_name='researcherpage',
            name='facets',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Facet'),
        ),
        migrations.AddField(
            model_name='themepage',
            name='facets',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Facet'),
        ),
    ]
