# Generated by Django 2.2.2 on 2019-08-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_field_facets_to_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherthemerelationship',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_researcher_relationship', to='core.ThemePage'),
        ),
    ]
