# Generated by Django 2.2.5 on 2019-09-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_textsearchpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facet',
            options={'ordering': ['title']},
        ),
    ]
